-   id: autopep8_quotes
    name: autopep8_quotes
    entry: autopep8_quotes
    language: python
    'types': [python]
    args: ["--diff", "--check-hard", "--recursive"]
    require_serial: false
    additional_dependencies: []
