language: python

python:
    - "3.7"
    - "3.8"

install:
    - python setup.py --quiet install

script:
    - python tests/test_unify.py

after_success:
    - pip install --quiet coverage
    - coverage run tests/test_unify.py
    - coverage report --show-missing --omit='*/distutils/*'; true
