name: Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        # https://help.github.com/articles/virtual-environments-for-github-actions
        platform:
          # - ubuntu-16.04
          # - ubuntu-latest
          # - macos-latest
          - windows-latest
        python-version:
          - 3.8

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

#    - name: Print listdir of directory
#      run: |
#        python -c "import os; print(os.listdir('./'))"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip wheel
        # Use the latest published version
        python -m pip install tox-gh-actions

    - name: Test with tox
      run: tox

    - name: The job has succeeded
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: create-artifact-logs
        path: .tox/checkonly/log


